name: Deploy to EC2
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: rnwxyz/ci-cd:latest
    
    - name: Deploy to EC2 by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          sudo docker stop app
          sudo docker rm app
          sudo docker pull rnwxyz/ci-cd:latest
          sudo docker run -d \
            -e "DB_USER=${{ secrets.DB_USER }}" \
            -e "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            -e "DB_HOST=${{ secrets.DB_HOST }}" \
            -e "DB_NAME=${{ secrets.DB_NAME }}" \
            -e "API_PORT=${{ secrets.API_PORT }}" \
            -e "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" \
          -p 80:80 --name app rnwxyz/ci-cd:latest